Telegram Bot implementation
gambe-ro/lobsters-twitter-bot pull request #1
Opened 2019-07-23 15:34 UTC by marcodenisi

### Description
Implement Telegram Bot using [this](https://python-telegram-bot.org/) library wrapping the standard Telegram API.

### Environment variables
Apart from the variables used in the Twitter implementation:
- **TOKEN**: the unique bot token
- **CHAT_ID**: the unique id representing the chat where the bot is admin

2019-07-23 15:44 UTC, karjudev commented on src/telegram_bot.py
> +FETCH_INTERVAL = int(getenv("FETCH_INTERVAL", default=900)) # in seconds
Dato che nel `README` è specificato che `FETCH_INTERVAL` è in minuti, moltiplicherei questo numero per 60.

2019-07-23 15:45 UTC, karjudev commented on src/telegram_bot.py
> +updater.start_polling()
Racchiuderei queste ultime righe in un `if __name__ == "__main__":`.

2019-07-24 13:33 UTC, karjudev commented on src/telegram_bot.py
> +	new_stories = get_new_stories(last_story, json)
Quando una nuova storia non può essere creata lancia un `ValueError`, occhio che venga tutto gestito a dovere come nel Twitter bot.

2019-07-26 06:51 UTC, chobeat requested changes

2019-07-26 06:51 UTC, chobeat commented on src/telegram_bot.py
> +last_story = None
avere uno stato globale così non è proprio il massimo. Sarebbe da spostare  un tot di questa roba dentro una classe, sia per chiarezza che per  manutenibilità.

2019-07-26 06:51 UTC, chobeat commented on src/telegram_bot.py
> +updater = Updater(token = TOKEN, use_context = True)
stesso discorso per questi pezzi. In Python normalmente si mettono in una funzione chiamata `main` e li si richiama al lancio del programma

2019-07-26 06:51 UTC, chobeat commented on src/telegram_bot.py
> +    try:
l'indentazione è sbagliata, questo programma probabilmente non è nemmeno eseguibile.

2019-07-26 06:51 UTC, chobeat commented on src/telegram_bot.py
> +	global last_story
da rimuovere quando si usa la classe

2019-07-26 06:51 UTC, chobeat commented on src/telegram_bot.py
> +job_minute = job_queue.run_repeating(publish_news, interval=FETCH_INTERVAL*60, first=0)
anche questo nel main

2019-07-26 14:53 UTC, marcodenisi reviewed
cambiamenti fatti

2019-07-26 19:22 UTC, chobeat approved these changes

2019-07-26 19:24 UTC, merged